modelname: iwslt_smoothML_l24_g32_attn
model : pervasive
default_config : config/default.yaml

loss:
  version : smooth_ml
  label_smoothing : 0.1

network :
  type: densenet
  num_layers : 24
  growth_rate : 32
  kernel : 5
  conv_dropout : .2
  bias : 0
  weigth_norm : 0
  init_weights: 0
  norm : batch
  use_st : 0
  half_inputs : 1

aggregator:
  mode : max-attention
  first_aggregator : max
  attention_dropout : .2
  scale_ctx : 1
  pool_kernel : 3
  pool_width : 8
  attend_kernel : 3
  pos_emb_dim : 64
  nonlin : none

data:
  src : de
  trg : en
  dir : data/IWSLT14_BPE_SHUFF_SORT_EVAL_V2
  batch_size: 16
  max_src_length : 70
  max_trg_length : 70


track: 
  batch_size : 4
  checkpoint : 8000
  max_length_a : 0
  max_length_b : 80

optim: 
  seed : 3
  max_epochs : 40
  LR:
      base : 0.0005
      decay_start : 0
      decay_every: 4
      decay_rate : 0.8
      patience : 3
      schedule: early-stopping
      criterion : loss
