modelname: iwslt_l24_log
default_config : config/pervasive.yaml

network :
  type: log-densenet
  num_layers : 24
  kernels: 3
  conv_dropout : .2

encoder:
  input_dim : 128

decoder:
  input_dim : 128

data:
  src : de
  trg : en
  dir : data/iwslt
  batch_size: 16
  max_src_length : 70
  max_trg_length : 70


track: 
  batch_size : 4
  checkpoint : 8000
  max_length_a : 0
  max_length_b : 80

optim: 
  seed : 3
  max_epochs : 40
  LR:
      base : 0.0005
      decay_start : 0
      decay_every: 4
      decay_rate : 0.8
      patience : 3
      schedule: early-stopping
      criterion : loss
